language: ruby
rvm:
  - "2.2.0"
  - "2.1.0"
  - "2.0.0-p598"
before_install:
  - "gem install tictactoe-core-0.1.0.gem"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "rake spec:ci"
